### ISSUE TITLE
Adding introduction/snippet for Boomerang-OpenTelemetry Plugin to the EUM documenation

### ISSUE THREAD

**Issue by Patrick-Eichhorn** [inspectIT/inspectit-ocelot#1011]
Appending information about the configuration of the [Boomerang-OpenTelemetry Plugin](https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin ) to the [EUM - Server Documentation](https://inspectit.github.io/inspectit-ocelot/docs/enduser-monitoring/install-eum-agent).

**Comment by mariusoe** [comment]
closed by #1013
