### ISSUE TITLE
Add support for w3c trace-context headers for OpenTelemetry interoperability

### ISSUE THREAD

**Issue by mc-chaos** [inspectIT/inspectit-ocelot#1040]
To use opencensus, jaeger  and opentelemetry Frameworks in the same environment, inspectIT should understand (and use) the w3c trace-context headers instant the b3 headers.

https://www.w3.org/TR/trace-context/

**Comment by mariusoe** [comment]
Hi @mc-chaos 

the agent is already able to handle multiple correlation header formats, including the trace context header and correlate incoming spans with it.

This was implemented in PR #793 

Is that what you mean by this ticket?

**Comment by mariusoe** [comment]
I've also added an ticket (#1044) to add this to the documentation, because it is currently missing there.

**Comment by mc-chaos** [comment]
@mariusoe , 
thx for your info. Yes, this was the Question. If there is a mixed environment with different tracing implementation, it needs to interoperate. Thx for the Docu Update.
Regards, Sascha

**Comment by mc-chaos** [comment]
close
