### ISSUE TITLE
The demo app doesn't work 

### ISSUE THREAD

**Issue by zzhao2010** [inspectIT/inspectit-ocelot#1093]
Hi,
I ran the demo app provided as per instruction. docker-compose -f docker-compose-prometheus-jaeger.yml up. However multiple services were not up and running properly. I saw this error message in the log.

api-gateway             | 2021-05-28 07:26:01.759  WARN 1 --- [nio-8080-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]
api-gateway             | 2021-05-28 07:26:02.768  WARN 1 --- [nio-8080-exec-2] o.s.c.n.z.filters.post.SendErrorFilter   : Error during filtering
api-gateway             |
api-gateway             | com.netflix.zuul.exception.ZuulException: Forwarding error
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:191)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:166)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:114)
api-gateway             | 	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117)
api-gateway             | 	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193)
api-gateway             | 	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157)
api-gateway             | 	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118)
api-gateway             | 	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96)
api-gateway             | 	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116)
api-gateway             | 	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81)
api-gateway             | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:44)
api-gateway             | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
api-gateway             | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
api-gateway             | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
api-gateway             | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
api-gateway             | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
api-gateway             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
api-gateway             | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
api-gateway             | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
api-gateway             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
api-gateway             | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
api-gateway             | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-gateway             | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-gateway             | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
api-gateway             | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
api-gateway             | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
api-gateway             | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
api-gateway             | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
api-gateway             | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
api-gateway             | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
api-gateway             | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
api-gateway             | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
api-gateway             | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
api-gateway             | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
api-gateway             | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api-gateway             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
api-gateway             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
api-gateway             | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api-gateway             | 	at java.lang.Thread.run(Thread.java:748)
api-gateway             | Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: vets-service
api-gateway             | 	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
api-gateway             | 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
api-gateway             | 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
api-gateway             | 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
api-gateway             | 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
api-gateway             | 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
api-gateway             | 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
api-gateway             | 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
api-gateway             | 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
api-gateway             | 	at rx.Subscriber.setProducer(Subscriber.java:209)
api-gateway             | 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
api-gateway             | 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.subscribe(Observable.java:10423)
api-gateway             | 	at rx.Observable.subscribe(Observable.java:10390)
api-gateway             | 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
api-gateway             | 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
api-gateway             | 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:186)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.support.AbstractRibbonCommand.run(AbstractRibbonCommand.java:51)
api-gateway             | 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
api-gateway             | 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
api-gateway             | 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
api-gateway             | 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
api-gateway             | 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
api-gateway             | 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
api-gateway             | 	at rx.Observable.subscribe(Observable.java:10423)
api-gateway             | 	at rx.Observable.subscribe(Observable.java:10390)
api-gateway             | 	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
api-gateway             | 	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
api-gateway             | 	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
api-gateway             | 	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
api-gateway             | 	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:161)

**Comment by mariusoe** [comment]
Hi @zzhao2010 

thanks for testing inspectIT Ocelot.
We are aware that there is currently a problem with the demo. As far as I know, this problem is related to the default Docker network.

We'll let you know when we've more informations about this problem and how it can be solved.
