### ISSUE TITLE
Create agent command for fetching details about an agent

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1124]
In this ticket, an agent command should be implemented for the agents and configuration server, in order to be able to request details about specific agents.

This details should include:

- existing environment variables
- existing Java system properties
- existing JVM arguments
- Java Version of the application
- Operating System
- the start command of the application itself (if possible)

These information should be able to rerieved via an GET endpoint on the configuration server, e.g.: `/api/v1/command/environment`

**Comment by heiko-holz** [comment]
Should it also include the currently running configuration?

The configuration used by the agent is not necessarily the same as the one specified in the ConfigServer, i.e.,
- the last fetched configuration is older as the configuration in the server;
- the configuration specified in the ConfigServer leads to an invalid configuration, which will be rejected by the agent. In this case, the agent uses the latest working config (I think)
