### ISSUE TITLE
Implement API endpoint for triggering a synchronization of the local workspace branch with a remote branch

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1137]
In this ticket, an API endpoint should be created which can be used for triggering a configuration synchronization. In this case, the synchronization pulls changes of a remote branch into the local workspace. Optionally, an auto promotion of all changed files can be triggered.

**Comment by mc-chaos** [comment]
Hi @mariusoe , Is this not implemented ? I think, we have this running.
Regards, Sascha

**Comment by mc-chaos** [comment]
Hi @heiko-holz , @MariusBrill , @ClaudioWaldvogel 
i think this Issue is done ? Would be cloused?
Regards, Sascha

**Comment by heiko-holz** [comment]
This ticket was not implemented, as the idea in #1138 was discarded
