### ISSUE TITLE
Error Lauching docker-compose to DEMO Prometheus and Jaeger Scenario

### ISSUE THREAD

**Issue by diegoquirino** [inspectIT/inspectit-ocelot#1152]
**Given** that I'd downloaded [Inspectit Ocelot DEMO v1.11.1](https://github.com/inspectIT/inspectit-ocelot/releases/download/1.11.1/inspectit-ocelot-demo-1.11.1.zip)
_And_ unzipped files

**When** I ran command `docker-compose -f docker-compose-prometheus-jaeger.yml up` inside _extracted directory_

**Then** Servers should be up and running

**But** The error is shown to console and docker-compose exits with error: 

```
Error response from daemon: manifest for inspectit/inspectit-ocelot-configurationserver:1.11.1 not found: manifest unknown: manifest unknown
```

**Comment by Patrick-Eichhorn** [comment]
Hello @diegoquirino,
thanks for the information, I just saw that the Docker image has not been uploaded to Docker Hub yet after the release. I have just fixed this, now it should work. 

However, please note that the demo application is not fully working at the moment, as there is a bug in the application itself that is being monitored. We are currently working on the demo application to fix this.

**Comment by diegoquirino** [comment]
Thank you. _As a working arround, I've changed `.env` **version variable to 1.10.1**._
