### ISSUE TITLE
Extend the configuration UI to be able to hide files

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1187]
Currently, all existing configuration files are displayed in the configuration UI's file tree. In case many files and directory exists, this tree can become quite messy. It would be great to have an option to hide certain files.

In this ticket, the configuration UI should be extended, so that specific files can be hidden from the file tree. Here, it should be implemented in such a way that files whose names begin with a dot are hidden. This should be able to be switched on and off dynamically (e.g. using the context menu). Hidden files should also be hilighted in some way when they are displayed.

**Comment by Marcel-Haag** [comment]
Related MR: https://github.com/inspectIT/inspectit-ocelot/pull/1493
