### ISSUE TITLE
Enable uploading files and folders in the configuration UI

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1203]
Given I have multiple configuration files, potentially structured in folders, that I all want to upload to the configuration server, I either have to manually place them in the working directory or create each file and folder separately in the UI. Both are cumbersome. Instead, it would be great to have an option in the UI to upload one or multiple files and folders.

**Comment by heiko-holz** [comment]
Duplicate of #521
