### ISSUE TITLE
[Agent] Metrics are still reported with previous custom tag values if tag value is changed at runtime

### ISSUE THREAD

**Issue by matthias-huber** [inspectIT/inspectit-ocelot#1223]
Hello inspectIT Team,

according to https://inspectit.github.io/inspectit-ocelot/docs/metrics/common-tags#user-defined-tags it is possible to change a tag value at runtime.

I have started an application with -Dinspectit.config.file-based.path. The directory contains a properties file with the content "inspectit.tags.extra.mytag=valueAtStart". At runtime I changed the value of mytag to "valueChangeAtRuntime" and "valueChangeAtRuntimeSecond"

I had expected to see that the metric gets reported with the new values after each change. This works, however inspectIT still reports the metric for the old tag values with the latest numeric values before the tag value changed.

I assume that this behavior is not intended? If yes, maybe you can give me a hint where to look at in the code base so that I could try to provide a fix. So far, I have no clue where this might happen.

![potential_tag_bug](https://user-images.githubusercontent.com/13692153/135294466-016be029-d3bb-4302-9788-9374e312acf7.png)

**Comment by mariusoe** [comment]
Hi Matthias,

yes, that's a known "problem". Actually, it's not an agent thing but how
OpenCensus has been designed. Once a metric has been recorded, OpenCenus
will expose its latest value. There is no way in OpenCensus to drop unused
metrics, so they'll exist until the JVM is restarted. That's what happening
in this case.

This problem will be solved once we’ll have migrated to OpenTelemetry.
Then, the agent will provide the possibility to "drop" unused metrics in
order to free up memory and to keep things clean.

Matthias Huber ***@***.***> schrieb am Mi., 29. Sept. 2021,
16:56:

**Comment by mariusoe** [comment]
Your welcome :)

I'm closing the ticket. Feel free to reopen if you have further questions. Fyi: we're planning to migrate the agent to OpenTelemetry in the following months (October/November).
