### ISSUE TITLE
Allow configuring a base path for the configuration UI

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1239]
I would like to specify a base path under which the configuration UI is reachable. For instance, several pages of the UI can be accessed via the following URLs:
* `host:port/ui`
* `host:port/ui/login`
* `host:port/ui/configuration`
* etc.

I would like to configure a base path, e.g., `my-config-server` such that the pages can be accessed via:
* `host:port/my-config-server/ui`
* `host:port/my-config-server/ui/login`
* `host:port/my-config-server/ui/configuration`
* etc.

**Comment by mariusoe** [comment]
Duplicate of #601
