### ISSUE TITLE
Prometheus Exporter should be disabled by default

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1248]
Currently, the agent will always start an Prometheus endpoint for exposing its collected metrics. In case Prometheus is not used, this exporter has to be disabled on each agent. Furthermore, it is the only exporter that is started by default, due to the fact that it needs no specific configuration property like database URL.

It should be considered whether the Prometheus exporter could be disabled by default. In case it is used, it has to be enabled explicitly. This ensures that the agent does not unintended start the Prometheus exporter in case it has been forgotten to disable.

**Comment by mariusoe** [comment]
As discussed, the Prometheus exporter should be deactivated by default in order to not confuse users and to make it consistent across all exporters. This also prevents an unintended metric export in case Prometheus is not used and at the same time it is not realized that it will be enabled by default.

This will be a breaking change, because configurations eventually must be adapted in case the Prometheus exporter is in use.

**Comment by heiko-holz** [comment]
We discussed the following approach that applies to **all** exporter services (i.e., Jaeger, Prometheus, Zipkin, Logging, InfluxDB etc.):

- all exporters are **not** enabled by default
- the `enabled` flag will be refactored (something like `enabledIfConfigured`) with new logic. The exporter will only be started when this flag is `true` **AND** when all necessary parameters have been configured. 
 - If possible, the value of this flag can be evaluated by `YAML`
 - it would be nice if the exporters could be enabled by changing only one attribute, e.g., exporter that have no parameters (such as logging, will have `enabledIfConfigured=false`. Exporters that need specified parameters could come with default parameters (such as Prometheus), but `enabledIfConfigured` set to `false` if all required parameters are set by default. Then changing the flag would start the exporter.

**Comment by mariusoe** [comment]
As discussed, we'll use an ENUM with different values like `ENABLED`, `DISABLED`, `IF_CONFIGURED` instead of just a boolean flag.
