### ISSUE TITLE
Full configuration reference missing

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#1257]
Is there somewhere the full configuration reference available. I think this was available in the documentation before, but can not find it anymore.

**Comment by mariusoe** [comment]
Hi Ivan,

nice to hear from you! :)

What do you exactly mean with "full confiugration reference"?
The documentation is available at http://docs.inspectit.rocks/

Or do you mean some kind of overview of all configuration properties in some kind of table?
This is not there at the moment, but currently, we are working on an improved (agent configuration) documentation including generated configuration overviews (https://github.com/inspectIT/inspectit-ocelot-configuration-docs).

**Comment by ivansenic** [comment]
I remember in the documentation there was a section with the `.properties` or `.yaml` file listing all the configuration options with comments about each one.. So I guess this one does not exist anymore? Any ETA on the content in the https://github.com/inspectIT/inspectit-ocelot-configuration-docs?

**Comment by mariusoe** [comment]
Hi @ivansenic 

no, unfortuently there is no section listing all configuration options. Maybe it can help if you look at the agent's default configuration. The individual options are also documented there: https://github.com/inspectIT/inspectit-ocelot/tree/master/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default

Regarding an ETA on the configuration docs, I assume this will be ready during the first half of Q1 2022

**Comment by ivansenic** [comment]
Yes that s what I was looking for. It used to be shown in the docs as well. Thanks, I am closing this one.
