### ISSUE TITLE
Use the rule name as default scope if the scopes map is "null"

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#126]
A common use case is the definition of one rule per scope.
In this case the user always has to write in the configuration of the rule that it uses the corresponding scope.
We should add a default behaviour that if the scopes map is null, the agent will use a scope with the same name as the rule if such a scope exists.
Note that we should not use this behaviour when the scopes map is specified as an empty map "{}".
We then should assume that the user wants no scopes by default. This will be most commonly used in the default configuration, for example for the "method_duration" rule.

**Comment by mariusoe** [comment]
This ticket will not be done because rules and scopes will have different names due to naming conventions of rules and scpes (`r_my_rule`, `s_my_scope`, ...), now.
Furthermore, this can lead to a lot of confusion if suddenly scopes are used or not used anymore if something is renamed.
