### ISSUE TITLE
Config UI allows downloading the agent logs

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1287]
The config UI shall have a button to trigger the agent command that returns the agent logs (#1284), potentially combined with the agent status (#1286). As an example, warning or error status might be shown by an icon, which could be clicked for getting the logs.

**Comment by mc-chaos** [comment]
Hi @Henning-Schulz , the OTel-Exporter has the ability to collect and transport Logs. So there needs only a OTel-Logs-Receiver in the config-srv.
Regards, Sascha

**Comment by Henning-Schulz** [comment]
Hi @mc-chaos, thanks for that hint! However, we don't want to stream all logs from all agent constantly. This would be too much overhead. The idea rather is to have a button that fetches the logs when needed (e.g., because something does not work). For that, the agent commands seem to be more appropriate and does not need any further components.

**Comment by heiko-holz** [comment]
Closed with #1454
