### ISSUE TITLE
Extend the Configuration UI so that the Configuration Documentation can be displayed

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1291]
The goal of this ticket is to extend the web UI of the configuration server by a new view showing a configuration documentation.

The displayed configuration documentation should refer to an agent mapping selected by the user. It should therefore be possible to select a specific agent mapping on the basis of its name. As soon as a user saves a configuration file, the documentation should be updated.

It would be good if the documentation can be displayed at the same time (side by side) to the configuration editor.

**Comment by MariusBrill** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ocelot-5d396ecb619de37f5badff47/issues/inspectIT/inspectit-ocelot/1291?planning-poker) with ZenHub @heiko-holz
