### ISSUE TITLE
Add exporter services for Jaeger proto and OTLP (OpenTelemetry Protocol) gRPC and http (tracing and metrics)

### ISSUE THREAD

**Issue by heiko-holz** [inspectIT/inspectit-ocelot#1297]
Implement and test exporter services for 
- `JaegerGrpcTraceExporterService` (see [jaeger-proto](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/jaeger-proto))
     - rename the existing `JaegerTraceExporterService` to `JaegerThriftExporterService`
- `OtlpGrpcTraceExporterService`, `OtlpGrpcMetricsExporterService`, `OtlpHttpTraceExporterService`, and `OtlpHttpMetricsExporterService`, see [otlp grpc](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp) and [otlp-http](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp-http)

**Comment by MariusBrill** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Ocelot-5d396ecb619de37f5badff47/issues/inspectIT/inspectit-ocelot/1297?planning-poker) with ZenHub @heiko-holz @mariusoe

**Comment by MariusBrill** [comment]
When merged, the results from #1248 should also be included.
