### ISSUE TITLE
Add influx 2.X exporter

### ISSUE THREAD

**Issue by MariusBrill** [inspectIT/inspectit-ocelot#1309]
The agent currently only supports influx 1.X, thus integrating it with influx 2.X is only doable with workarounds.

Addtionally, influx 1.X is [not supported anymore as of 2022](https://www.influxdata.com/blog/influxdb-oss-and-enterprise-roadmap-update-from-influxdays-emea/).

**Comment by mariusoe** [comment]
Hi,

yes, currently there is no metric exporter existing for InfluxDB 2. As soon as we've migrated to OTel, you could use the OTLP exporter to export metrics to an OTel Collector which can push the metrics into InlfuxDB 2.X
