### ISSUE TITLE
Enable downloading support archives from the configuration UI

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1333]
As a supporter, when receiving a support request, I would like to get a support archive from the user who reached out to me. This will speed up the support significantly, as I don't need to ask for details. The archive should contain at least the version, configuration, logs, and JVM parameters of the affected agent.

---

To get a support archive, there should be a possibility to select the agent for which a support archive should be created. A new button could be added to the "Agent Status" overview, which can be used to request a support archive.

If a support archive is created directly by the configuration server and not by the configuration UI, it has the advantage that they can also be created programmatically (e.g. via curl). In this case, the configuration server must be extended by a corresponding endpoint.

**Comment by Marcel-Haag** [comment]
Blocked by: https://github.com/inspectIT/inspectit-ocelot/issues/1396
