### ISSUE TITLE
Ability to export one or multiple configuration files via the configuration server's web interface

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1396]
As a user, I want to be able to download a configuration file (or a directory) directly via the configuration UI, so that I don't have to copy its content manually into a local file.

---

Currently, it is not possible to download one or multiple configuration files via the configuration UI. If a user wants to download a file, its content must be manually copied and pasted into a local file. For this reason, it should be possible that a file or a whole folder can be downloaded via the Web UI (e.g. by right-clicking with the help of a context menu of the file tree). If a single file is downloaded, then this file should simply be saved as normal YAML. If multiple files or entire folders are downloaded, they should be bundled into an archive so that there is just one file to download. Creating an archive should be done on the client side, so that the Configuration Server does not need to be extended by a new endpoint.

**Comment by Marcel-Haag** [comment]
Related MR: https://github.com/inspectIT/inspectit-ocelot/pull/1439
