### ISSUE TITLE
[Feature] - *search and replace with the editor at config-srv* 

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [inspectIT/inspectit-ocelot#1430]
**Is your feature request related to a problem? Please describe.**
At the inspect-IT Config-SRV Editor there is no "search and replace" feature. So one could not easy find and replace keywords in the editor.

**Describe the solution you'd like**
Add "search and replace" feature to editor.

**Comment by MariusBrill** [comment]
Hi @SaschaBrechmannVHV,

There is arleady such a feature. You can access the "search and replace" function by pressing `ctrl + h`
You can find a list of all shortcuts by clicking the question-Symbol (?) on the right-side above the editor.
