### ISSUE TITLE
[Feature] - Reintroduce service-name config for OTLP Exporters

### ISSUE THREAD

**Issue by MariusBrill** [inspectIT/inspectit-ocelot#1437]
**Is your feature request related to a problem? Please describe.**
Prior to version 2.0, all exporters had a tag `service-name` with which a constant tag could be added to the data indicating the service the data is send from. This feature should also be available for the new exporters introduced in version 2.0

**Comment by heiko-holz** [comment]
The `service-name` tag was removed from the exporter in v2.0.0 as it is not supported by OTEL.
With OTEL, we can have one service name per agent, not per exporter.

Please use the global `inspectit.service-name` property.

see also documentation: https://inspectit.github.io/inspectit-ocelot/docs/tracing/trace-exporters

**Comment by SaschaBrechmannVHV** [comment]
A little bit more documentation, how to use this tag will be helpfull.
Solved on our site like this:
`
inspectit.service-name: '${inspectit.tags.extra.application:undefined_application}'
`
