### ISSUE TITLE
[Feature] - The service-name property of tracing exporter settings should be configurable during runtime

### ISSUE THREAD

**Issue by heiko-holz** [inspectIT/inspectit-ocelot#1450]
**Is your feature request related to a problem? Please describe.**
Currently, the `service-name` property of the `inspectit.exporters.tracing` settings only take effect when starting the agent. When the property is changed during runtime, it only takes effect after the agent has been restarted.

**Describe the solution you'd like**
Changes of the `service-name` property should take effect during runtime.

**Comment by MariusBrill** [comment]
Duplicate of #1442
