### ISSUE TITLE
Migrate web-UI to PrimeReact version 8.1.1 

### ISSUE THREAD

**Issue by Marcel-Haag** [inspectIT/inspectit-ocelot#1452]
We want to use the newer features from prime react.
Currently we use version `4.2.1` and we want to migrate to the latest version `8.1.1`.

Hints:
https://www.npmjs.com/package/primereact?activeTab=versions
https://www.primefaces.org/primereact/

**Comment by salim-1997** [comment]
The latest version of Primereact (v8) would require a premium theme implementation. Since the `nova-dark` theme, that was used, is deprecated after version 6. 

for more info about the deprecated theme:
https://github.com/primefaces/primeng/issues/6198

**Comment by heiko-holz** [comment]
Implemented with https://github.com/inspectIT/inspectit-ocelot/pull/1517
