### ISSUE TITLE
Circular reference in ContextManager prevents agent from start-up

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#150]
The `ContextManager` uses a reference on the `InstrumentationConfigurationResolver` which contains a circluar reference back to the `ContextManager` via the remote special sensors.

This problem occurs only occasionally and could be fixed by removing the `InstrumentationConfigurationResolver` from the `ContextManager` and using the `InstrumentationConfigurationChangedEvent` instead in order to store the data providers in a field.

**Comment by JonasKunz** [comment]
After some more thinking I found that the solution will not work. An `InstrumentationConfigurationChangedEvent` is only raised when the configuration changes, not when it is first loaded. I think the cleanest solution is to remove the `@DependsOn` annotation from the special sensors, as it is not really needed. They access the context manager anyway through the bootstrap.
