### ISSUE TITLE
[Bug] - Search functionality in documentation for v2.1.1 and v1.6.1 not working

### ISSUE THREAD

**Issue by heiko-holz** [inspectIT/inspectit-ocelot#1522]
**Describe the bug**
The search functionality of the documentation for [v2.1.1](https://inspectit.github.io/inspectit-ocelot/docs/doc1) and [v1.6.1](https://inspectit.github.io/inspectit-ocelot/docs/1.16.1/doc1) is not working anymore.

It works for the previous versions

**To Reproduce**
1. Go to  [v2.1.1](https://inspectit.github.io/inspectit-ocelot/docs/doc1) or[v1.6.1](https://inspectit.github.io/inspectit-ocelot/docs/1.16.1/doc1) i
2. Type something in the search and hit enter

**Comment by aaronweissler** [comment]
Works again now :) 
It was probably that the search index had not yet been updated by Algolia
