### ISSUE TITLE
 [Bug] - OtlpTraceExporterService does not expose configruations for underlying 

### ISSUE THREAD

**Issue by ClaudioWaldvogel** [inspectIT/inspectit-ocelot#1535]
**Describe the bug**
OtlpTraceExporterService uses ```io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter``` internally. But does not expose configuration values for e.g. headers.
Thus, it is not possible to authenticate against a basic auth secured OTEL Collector.

**Expected behavior**
It is possible to configure headers and for OtlpTraceExporterService

**Comment by heiko-holz** [comment]
Was closed by #1536
