### ISSUE TITLE
[Bug] - Agent Tests for sgrio/java:jdk_11_ubuntu regularly fail

### ISSUE THREAD

**Issue by heiko-holz** [inspectIT/inspectit-ocelot#1537]
**Describe the bug**
The [Agent Tests (sgrio/java:jdk_11_ubuntu)](https://github.com/inspectIT/inspectit-ocelot/actions/runs/3445568815/jobs/5749432581#logs) regularly fail.

**Expected behavior**
The agent tests for `sgrio/java:jdk_11_ubuntu` should not fail regularly due to "hiccups"

**Comment by quandor** [comment]
Can we close this bug? We no longer have agent tests using that image.
