### ISSUE TITLE
Add more OpenCensus exporters

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#169]
We agreed on adding the following exporters to the agent:
* Haystack (Tracing)
* SingalFX (Stats)
* OpenCensusAgent (Tracing)
* OpenCensusAgent (Metrics)

**Comment by mariusoe** [comment]
Please start with the OCAgent exporters because we'll need them at first.

**Comment by tangerstein** [comment]
Already started doing this in parallel ... should not take to much time from now on ...
