### ISSUE TITLE
Documentation issue 

### ISSUE THREAD

**Issue by gsmba6** [inspectIT/inspectit-ocelot#189]
The best way to start using inspectIT Ocelot is to attach the java agent when starting your Java program. Use the -javaagent command-line option to reference the inspectIT Ocelot jar:

$ java -javaagent:"/path/to/inspectit-ocelot-agent-0.1.M3.jar" -jar my-java-program.jar

I have attached the agent. now how agent will communicate with open census??

**Comment by AlexanderWert** [comment]
Hi @gsmba6,

you can find the current documentation for inspectIT Ocelot here:
http://docs.inspectit.rocks/releases/latest/

Today we will also launch our new website for inspectIT Ocelot under https://inspectit.rocks where you will find more information.

We also have a new Gitter channel if you have further questions:
https://gitter.im/inspectIT/Ocelot

Regards,
Alex

**Comment by mariusoe** [comment]
Hello @gsmba6

we use OpenCensus internally as a framework/library, so there is no standalone component which is used by the agent.

When you've attached the agent, by default it exposes a HTTP endpoint (port 8888) where all metrics are exposed in the Proemtheus format.

Using this endpoint, you can, for example:

- use Prometheus for scraping the metrics and storing them in Prometheus itself
- use Telegraf to scrape the metrics and write them into InfluxDB
 
We provide a containerized demo for both scenarios where you can find more information, e.g. how to set them up: http://docs.inspectit.rocks/releases/latest/#_inspectit_ocelot_demo
