### ISSUE TITLE
Provide basic UI, which uses mocked endpoints of the configuration server.

### ISSUE THREAD

**Issue by tangerstein** [inspectIT/inspectit-ocelot#209]
- Provide simple file tree (e.g. https://github.com/storybooks/react-treebeard)
- Provide simple yaml file Editing (e.g.https://github.com/securingsincity/react-ace)
- (Dummy) REST endpoints are used

- The user should be able to GET all existing files
- Optional: The user should be able to CREATE new files, DELETE files and UPDATE file with content X

**Comment by mariusoe** [comment]
Done by #283
