### ISSUE TITLE
Implement logic for managing the configuration directory structure

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#280]
This ticket implements the logic of the basic config-file view component to manage the configuration directory structure.

The following actions should be implemented
* Fetching the current file structure
* creating (sub)directories
* deleting directories
* create new files
* delete files

**Comment by JonasKunz** [comment]
This also incldues the abilitity to move files or directories.

**Comment by mariusoe** [comment]
Closed by #306
