### ISSUE TITLE
Implement more efficient scanning for OcelotPlugins

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#314]
Currently we use the "Reflections" library for scanning for classes which are annotated with "OcelotPlugin". This is very inefficient as it scans the entire classpath instead of a single Jar file.
We can improve this by first enumerating all files in the file via the Java JarFile class.
Afterwards using ASM the .class files can be parsed and checked for the "OcelotPlugin" annotation.

**Comment by mariusoe** [comment]
Please check if Spring provides a classpath scanner utility which can be used instead ASM. I assume this can be more easily.
