### ISSUE TITLE
Provide audit log for the configuration server

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#374]
Many users require to have some kind of audit log for each components which can be configured and modified by end-users.

Due to this reason, the configuration-server should log each modification of any kind of data (agent mappings, configuration changes, user added, ...) in the normal log stream. The log entry should contain the used username and the type of data which has been changed.
If availalbe, it would also be helpful to log what was changed (e.g. certain user has been created, ...).

**Comment by abhishekb03** [comment]
@mariusoe May I work on this?
