### ISSUE TITLE
Hook remains deactivated after instrumentation change if its configuration is not changed

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#392]
Assuming the following scenario: an action A uses a data element which is collected by an action B. If the action A and B are in separate rules and the data collected by B is up-propagated thus action A can use it.

If the data element is invalid causing an exception, hook A is getting deactivated. When fixing the caputre logic in hook B, hook A remains inactive after instrumentation change because its configuration has not been changed.

This means that an action / hook keeps inactive until its configuration is changed. This behavior has to be changed, e.g. reactivating all inactive hooks after reinstrumentation.

**Comment by JonasKunz** [comment]
I will also enhance the behaviour ensuring that all hooks get activated atomically.
