### ISSUE TITLE
Versioning for configurations and agent mappings

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#414]
In this epic, a versioning of configuration files and agent mappings should be introduced.

Currently, all configurations and agent mappings are stored in files located in the config-server's working directory and will be overwritten if its content is changed. This means that in case of a wrong or unwanted change, the previous content is lost.

In order to prevent this, a versioning should be introduced. Any change should be reflected in a new file version. It should be able to restore a certain version of a file.
The server will use and provide the latest version of a configuration file to the agents.

Furthermore, a staging should be introduced which means that a file can be changed but not triggering a new file version. By doing this, a "dirty" state of the configuration file can exist, which is not versioned, thus, not delivered to the agents. This can be considered as a "work in progess" file which will be used when it is "promoted" to a new file version.

In the configuration server's web UI, it should be able to see existing file versions and restore previous ones. Furthermore, it should be possible to "promote/active" changed files.

**Comment by mc-chaos** [comment]
Is this issue not solved with the New git Integration?
