### ISSUE TITLE
Add an endpoint for fetching all default configuration files

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#451]
The configuration server should have an endpoint where all default configuration files can be fetched at once.
The result Json should have the following form:
```
{
"Path/to/fileA": "<contents of A>",
"Path/to/fileB": "<contents of B>",
...
}
```

**Comment by mariusoe** [comment]
What is the purpose why the server should have this functionality?
I mean the agents wouldn't need such endpoint because they always have the default configuration available.

**Comment by JonasKunz** [comment]
This endpoint is there for the UI: The goal is to have the default configuration visible alongside with the custom config files in the configuration server.
