### ISSUE TITLE
Implement basic stack-trace sampling

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#487]
The goal of this ticket is to introduce a very minimal functional stack trace sampling to ocelot.

**Comment by mc-chaos** [comment]
Is this issue solved with the New release 1.6?

**Comment by mariusoe** [comment]
This ticket has been done. See: https://inspectit.github.io/inspectit-ocelot/docs/instrumentation/rules#auto-tracing
