### ISSUE TITLE
Have a possibility to label different instances of same service

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#50]
We need an `instance` tag that would set by default and which would report the instance id of the running service. In the future, we can read this information from the env vars if a service run on a specific could platform or service.

OpenCensus already has some means of reading the env information from AWS, k8s and Azure, maybe we could pull this in as well. However, this information is not related to the instance id, but more to region, etc.

**Comment by mariusoe** [comment]
This functionality can be achieved using the common tag feature.

https://inspectit.github.io/inspectit-ocelot/docs/metrics/common-tags
