### ISSUE TITLE
Implement endpoint for the config-server to search the configuration files' content

### ISSUE THREAD

**Issue by mbrill-nt** [inspectIT/inspectit-ocelot#560]
We need a function to search for files based on their contents. This function would take a search string as an argument and returns the names of all files which contain this search string.

**Comment by AlexanderWert** [comment]
"... and retunrs the names of all files..."  
--> Plus the corresponding line numbers in the files where the string has been found

**Comment by mariusoe** [comment]
The response of the endpoint should contain JSON object which describes the search hits.

A hit could be something like:

```
{
    start: {
        line: 10,
        position: 40
    },
    end: {
        line: 10,
        position: 50
    }
}
```

,where the line represents the line-number of the hit and position the character index of the start or end, respectivelly.

The search term should be passed to the endpoint via a request parameter. The endpoint could be look like: `.../search?q=search_term`
In this exmaple, the parameter `q` stands for "query".
