### ISSUE TITLE
Auto-completion sometimes shows duplicated entries

### ISSUE THREAD

**Issue by AlexanderWert** [inspectIT/inspectit-ocelot#565]
Sometimes the popup for the auto completion in the config UI shows duplicated entries:

![image](https://user-images.githubusercontent.com/866830/74711629-c4117480-5224-11ea-918c-37334ddb9944.png)

**Comment by JonasKunz** [comment]
I guess I found the root cause in `OcelotAutoCompleter.js`:
```
export const enableOcelotAutocompletion = (aceEditor) => {
  if (!initialized) {
    const langTools = ace.require('ace/ext/language_tools'); // eslint-disable-line no-undef
    langTools.addCompleter(completer);
  }
  aceEditor.configAutoCompleteEnabled = true;
};
```
We check the `initialized` flag, but never set it.
This function is called whenever the Editor is created, causing the autocompleter to be registered multiple times.
