### ISSUE TITLE
Remove is-tag data property 

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#566]
Implementing the #563 makes use of `is-tag` data property obsolete. As we will need to create an explicit tag context when recording metrics, we don't need any more to maintain the globally the tag context when propagating data.

This means that:
* we can remove property `is-tag` from the `DataSettings`
* we can remove `isTag`, `setTag` from the PropagationMetaData interface and implementing classes
* we can simplify the `InspectitContextImpl` and remove any maintenance of the TagContext, the up and down propagation would only depend on the respected props in the `DataSettings`

This would also mean we could get a performance improvements on the context changes for a penalty of creating a local tag context per metric recording.

**Comment by JonasKunz** [comment]
A tag context is opened by the inspectIT context only if oepn-ensus is pushed to the bootstrap.

If we want to keep inter-operability (e.g. inspectIT tags are visisble for metrics captured via manual instrumentation), then the is-tag proeprty is still required.

**Comment by ivansenic** [comment]
@JonasKunz Great info.. I won't touch this for now..

**Comment by mariusoe** [comment]
This issue is not valid because the mentioned property is still needed.
