### ISSUE TITLE
Extend the tracing capabilities to set a span's status

### ISSUE THREAD

**Issue by AlexanderWert** [inspectIT/inspectit-ocelot#588]
Currently, all collected spans provides a status attribute which is set to `Status.OK`.
This status attribute will be used by certain tracing backend systems for e.g. visualization or grouping of collected spans.

In this ticket, the ability should be implemented to assign a custom status to a span.

Using OpenCensus, a span's status is set as following:

```
span.setStatus(Status.NOT_FOUND.withDescription("Cache miss"))
```

It should be able to set the status using a constant value or dynamically via the data context.

**Comment by JonasKunz** [comment]
I would suggest that we start with only error / success status, to keep it simple for now.
This is sufficient to visualize the errornous spans in the tracing backends, details liek the http status or error messages can already be added as attributes to spans.

I would suggest the following configuration approach:
```
my_rule:
  tracing:
    error-status: my_data_key
```
When the instrumented method finishes, the given data key is read and "interpreted" as error status. This means, if the value is neith `null` nor `false`, the span is marked with the OpenCensus `UNKOWN` status code, which seems to be the general purpose one.

Why `null` or `false`? I have the following two use-cases in mind:

```
first_rule:
  tracing:
    error-status: _thrown
second_rule:
  tracing:
    error-status: is_error
```

The first rule most-likely is the 99% case: make the span as an error, if any exception was thrown.
The second rule is for special stuff, such as http: here we can derive the `is_error` booelan for example from the http_status code and therefore mark the span accordingly.
