### ISSUE TITLE
Implement a basic JMX metrics recorder

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#606]
In this ticket, a basic JMX recorder should be implemented.

- The recorder records all numeric JMX attributes as tagged metrics.
- Boolean attributes should be converted (`false` -> `0`, `true` -> `1`).
- The metrics should be **tagged using the existing common tags**.
- The metrics should share a **common metrics prefix**.
- The resulting metric should be tagged using the **mbean** and **attribute name**.

**Comment by ivansenic** [comment]
@JonasKunz @mariusoe As I mentioned this, JMX exporting is already done in the https://github.com/prometheus/jmx_exporter repository.

The beauty is that they have the [JmxScraper](https://github.com/prometheus/jmx_exporter/blob/master/collector/src/main/java/io/prometheus/jmx/JmxScraper.java) class, which has an "recerder" interface.. Thus we would be able to directly take this and avoid any implementation for scraping. We only need to add a way to transform data collected to anything we want. Thus, speed us up a lot.

What do you say?

**Comment by JonasKunz** [comment]
Sure, I think we can just copy this class and clean it up a little, as we don't need the remote jmx connection ability.

Make sure to avoid using lists in our configuration model, as they cannot be merged across files.
