### ISSUE TITLE
Data provider for the HTTP server request properties

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#62]
Showcase the possibilities of #61 by implementing the data provider for the HTTP request on Servlet API 3.x.

Analyze if @JonasKunz idea about the JavaAssist compile code can be already used here or we should go for reflection. The old inspectIT project is helpful here as we already have full support there.

**Comment by mariusoe** [comment]
Done. The capabilities of the data providers have been succesfully shown and verified by various system tests.

The implementation of the metric collection of HTTP servlet metrics was done already in ticket #63
