### ISSUE TITLE
Collect the HTTP request metrics for the Servlet API 3.x

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#63]
Collecting metrics about the 

* response time
* error count

for incoming HTTP requests. Use tags provided by the HTTP server data provider.

We need to support async servlet execution as well, thus this is a perfect moment to analyze all possibilities about the metric collection in case of async action. We should start by checking how do the special sensors help here (if at all). If they are not, we need a way of attaching the start time (or actually anything else to a request object). This would extend the process in our mind map.

System test: spin up the HTTP server and do a request against it. Test error case as well.

**Comment by mariusoe** [comment]
Closed in #149 

The asynchronous servlet processing will be handled in issue #152
