### ISSUE TITLE
Add support for percentiles of metrics

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#665]
The goal of this epic is to add support for percentile views of metrics.
At the moment only averages and histograms can be collected for response times, which severly limits the analysis capabilities for response times.

For this reason we will add a percentile view, which exposes specified percentile values of a metric within a sliding time window.

**Comment by mariusoe** [comment]
Closed.

#681 is handled separately because of its lower priority.
