### ISSUE TITLE
Span context propagation for the java.net.URLConnection

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#67]
Enrich the exit point to propagate the current span context. The implementation exists in the old inspectIT project and can be used if the interfaces are based on the OC. Figure our how can the `Tracestate` be altered by us in order to inject flow-map based tags.

Note that implementation should be generic and should require only a proper injector to be bounded to exit point.

System tests can be done with the Wiremock to provide that the correct headers are injected.

**Comment by JonasKunz** [comment]
Already implemented
