### ISSUE TITLE
Enable tracing for entry points

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#69]
Implement the method tracing based on our mind map. The entry-point should check if the remote context is available and if not check with sampler if tracing should be done or not. Don't cover non-entry point tracing impl in this issue. Add context key/value pairs to the span as the attributes.

System test: send a request to the own HTTP server with remote context and prove its passed on.

**Comment by JonasKunz** [comment]
Already fixed with our tracing implementation
