### ISSUE TITLE
Upgrade Service Dependency Graph pluging of demo scenarios to the latest version

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#713]
Currently, the Ocelot demos cenarios use an outdated version of the Service Dependency Graph plugin, which misses a lot of new features and improvements. 

The plugin should be upgraded to the lastest version and the related dashboards have to be adapted.

**Comment by mc-chaos** [comment]
Was this not closed with #727 ?

**Comment by mariusoe** [comment]
Thanks @mc-chaos for the hint!

Closed by #727
