### ISSUE TITLE
Context propagation for sending JMS message

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#72]
Copy from the old inspectIT, should be straight forward if implemented after `M3`.

Add system test with mocked JMS impl.

**Comment by mc-chaos** [comment]
Is this relevant any more? JMS Monitoring works long time ago

**Comment by mariusoe** [comment]
Hello @mc-chaos , this ticket is still open because the default configuration does not cover JMS data, yet. I've created a new ticket for this, because only a configuration has to be created here.

Closed in favor for #781
