### ISSUE TITLE
Problem with http traces

### ISSUE THREAD

**Issue by GuazP** [inspectIT/inspectit-ocelot#723]
Hi,

I managed to get some spans in jaeger and i trying to get traces of http between `app.jar` and `elasticsearch` (both are in separate containers). This app sending request with post method to elasticsearch. But I have few errors from many sides, and I don't know what to deal with it. Even 'action' with regex from demo app causes error. Maybe i do something wrong and someone can point me where it is?

My config.yml on ocelot-config-server side:
```
inspectit:
  instrumentation:
    scopes:
      example_scope:
        superclass:
          name: "my.package.*"
          matcher-mode: "CONTAINS"
        advanced:
          instrument-only-inherited-methods: false
          disable-safety-mechanisms: true
    rules:
      'http_parametrize_path':
        include:
          'parametrize_elasticsearch_paths': true
      'parametrize_elasticsearch_paths':
        entry:
          'http_path':
            only-if-not-null: 'http_path'
            action: 'a_regex_replaceMatch'
            data-input:
              'string': 'http_path'
            constant-input:
              'pattern': '\/elasticsearch\/.+\/.+'
              'replacement': '/elasticsearch/{service}/{location}'
  exporters:
    tracing:
      jaeger:
        enabled: true
        url: http://jaeger:14628/api/traces
        service-name: ${inspectit.service-name}
```
exceptions.log:
```
020-05-06 09:14:25,767 WARN  8018460 --- [api-gateway] [pectit-thread-0] StringToMetricRecordingSettingsConverter : You are using the deprecated map-based configuration style for recording metrics. This style will be invalid in future ocelot releases.
2020-05-06 09:14:26,295 ERROR 8018988 --- [api-gateway] [pectit-thread-0] r.i.o.core.config.InspectitEnvironment   : Error loading the configuration 'inspectit'.
2020-05-06 09:14:26,295 ERROR 8018988 --- [api-gateway] [pectit-thread-0] r.i.o.core.config.InspectitEnvironment   : instrumentation.rules.parametrize_elasticsearch_paths.entry.http_path => Action with name 'a_regex_replaceMatch' does not exist!
2020-05-06 10:10:29,227 WARN  11381920 --- [api-gateway] [pectit-thread-1] r.i.o.c.config.PropertyNamesValidator    : The specified property 'inspectit.instrumentation.rules.http_parametrize_path.include.parametrize_elasticsearch_paths' does not exist! 
```
Container output:
```
May 06, 2020 9:16:11 AM org.elasticsearch.client.RestClient logResponse

WARNING: request [POST http://elasticsearch:9200/dashboard_problems/_doc/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512] returned 1 warnings: [299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[types removal] Specifying types in search requests is deprecated."]

May 06, 2020 9:16:12 AM org.elasticsearch.client.RestClient logResponse

WARNING: request [POST http://elasticsearch:9200/dashboard_flight_delay/_doc/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512] returned 2 warnings: [299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."],[299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[types removal] Specifying types in search requests is deprecated."]

May 06, 2020 9:16:12 AM org.elasticsearch.client.RestClient logResponse

WARNING: request [POST http://elasticsearch:9200/dashboard_problems/_doc/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512] returned 2 warnings: [299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."],[299 Elasticsearch-7.5.2-8bec50e1e0ad29dad5653712cf3bb580cd1afcdf "[types removal] Specifying types in search requests is deprecated."]
```

Someone maybe see where is my fault? Or how to adjust to 'up-to-date' my try to get http traces?

**Comment by mariusoe** [comment]
Hi @GuazP 

can you tell us which version of the agent you are using? If you're using the agent in version 1.2, it will not work because you're using a feature which will be part of the 1.3 release - the rule-inclusing:
```
'http_parametrize_path':
        include:
```

Beside of that, ensure that your scope is actually matching some classes. It looks like that you didn't adjust the superclass matcher to your case but using the deocumentation example value of `my.package.*`

Other that that, it should work with your configuration.

**Comment by GuazP** [comment]
Thank you for reply @mariusoe.

> Beside of that, ensure that your scope is actually matching some classes. It looks like that you didn't adjust the superclass matcher to your case but using the deocumentation example value of `my.package.*`
This 'my.package.*' is replaced by me, I changed it of course, and adjust for project.

> can you tell us which version of the agent you are using? If you're using the agent in version 1.2, it will not work because you're using a feature which will be part of the 1.3 release 
I get this scheme from demo downloaded like 2-3 weeks ago, so it looks like demo had this 'feature in configs' before 1.3 release, maybe this is reason why this demo didn't work for me at all :).
Anyway, is there any replacement, or I just have to get 1.3 version and it would be the most simple way?

**Comment by GuazP** [comment]
And if you talking about release 1.3, where I can find it, because for now I didn't see it:
https://github.com/inspectIT/inspectit-ocelot/releases
The last one I see, is 1.2.1, docs are also have only 1.2 version in header :)

**Comment by mariusoe** [comment]
We just releases it so you had to built it by yourself.
Now, you can find it in the releases section of this repository.

**Comment by GuazP** [comment]
Yea, I updated agent and server-config.

For now previous functionality to instrument lambda is working (no such error occures), and my app is evaulated with lambdas because it is working on akka cluster.

Now in exceptions.log and output i have same error, in exceptions.log are full stack of it:
```
2020-05-08 08:19:35,295 ERROR 11475  --- [api-gateway] [pectit-thread-1] r.i.o.c.i.InstrumentationTriggerer       : Error retransforming class 'de.isogmbh.rom.frontend.problem.ProblemStreamProcessingActor$$Lambda$1076/801197022'
java.lang.VerifyError: null
    at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
    at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
    at rocks.inspectit.ocelot.core.instrumentation.InstrumentationTriggerer.checkClassesForConfigurationUpdates(InstrumentationTriggerer.java:163)
    at rocks.inspectit.ocelot.core.service.BatchJobExecutorService.lambda$startJob$0(BatchJobExecutorService.java:126)
    at rocks.inspectit.ocelot.core.service.BatchJobExecutorService$BatchJob.lambda$new$0(BatchJobExecutorService.java:83)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:747)
```
This wouldn't happen before.

And this configuration which I send when starting this issue, still isn't work at all, maybe becouse this error... But idk really. Any ideas?

**Comment by mariusoe** [comment]
Hi @GuazP 

I hope your problem has been solved.
One more addition: for HTTP tracing in version 1.3 only the exporter must be activated - no further configuration is necessary

**Comment by GuazP** [comment]
Yes, it works now.
