### ISSUE TITLE
There are differences with EJB than other classes in instrumentation?

### ISSUE THREAD

**Issue by GuazP** [inspectIT/inspectit-ocelot#736]
Hi,

I have some traces from app, and i trying to get some trace from another one. I had no errors from my config, and as far as I read documentation. I didn't know what I should add to get some output in jaeger. There is my instrumentation (yml file):
[ejb_scope.yml](https://github.com/inspectIT/inspectit-ocelot/files/4609619/ejb_scope.txt)
Type is my class with method login which implement javax.ejb.Stateless this way:

```
import javax.ejb.Stateless;
import javax.ws.rs.Path;

@Stateless
@Path("some_path")
public class CommonOperativeLoginInterfaceFacade implements LoginService {
```

Maybe I missed something when I want to get this trace in jaeger? Some export rules?

Tracing is mapped like with other app, so this shouldn't be a problem.

**Comment by mariusoe** [comment]
Hey @GuazP 

looks like you're trying to match the `Stateless` annotation but using interface matchers instead of annotation ones.

**Comment by GuazP** [comment]
Thank you :)
