### ISSUE TITLE
Ejb matching

### ISSUE THREAD

**Issue by RRadziejewski** [inspectIT/inspectit-ocelot#737]
Hi, Thanks for all the help i've ben gifted by @mariusoe @JonasKunz so far.

I am writing because i didn't get success in matching my class which is annotated with interface Stateless. Here is my example scope:

`   
example_scope_ejb1:

        interfaces:
          - name: "javax.ejb.Stateless"
            matcher-mode: EQUALS_FULLY
            annotations:
              - name: 'javax.ejb.Stateless'
                matcher-mode: EQUALS_FULLY
`

This is my class definition:

`@Stateless

@Path("common/v1")
public class XXXXXXXXXXXXXX implements XXXXXXXXXXXService 
`

How to mach against all classes with Stateless annotation ?
What is missing in my scope ? i would really appreciate your help.

Do i need to match against @Path annotation also ? How then i can Match against others @stateless annotated classes which might have many more annotations.
What am i missing there ?

My rule at the moment is fairly easy i want entry of methods in this scope:

`
example_rule_ejb1:

        scopes:
          example_scope_ejb1: true
        tracing:
          start-span: true
`

**Comment by AlexanderWert** [comment]
Hi @RRadziejewski ,

for your example code you need the following scope config:
`inspectit:
  instrumentation:
    scopes:
      's_ejb_scope':
        interfaces:
          name: 'Service'
          matcher-mode: ENDS_WITH
        type:
          annotations:
            - name: 'javax.ejb.Stateless'
              matcher-mode: EQUALS_FULLY`

The interfaces part matches all classes that implement interfaces ending with "Service". The second part is "and"-concatenated, thus, in addition all of the classes must have the annotation "javax.ejb.Stateless".

**Comment by RRadziejewski** [comment]
@AlexanderWert Thanks for your reply,

Can i somehow match all classes which have just annotations ?

**Comment by mariusoe** [comment]
Yes, you could use the scope which Alex has posted and remove the interface matcher.

**Comment by RRadziejewski** [comment]
Yep that's what i did Thank you @AlexanderWert @mariusoe
