### ISSUE TITLE
How to include input and output data to traces.

### ISSUE THREAD

**Issue by GuazP** [inspectIT/inspectit-ocelot#740]
Hi,

I trying to get more data with traces. We with @Rafał have general case (thanks to you) with ejb annotations, and we want to know what these methods have as input arguments, and what returns. It's possible to do this with general scope? Or to get this we need to specify every method by detail?

There is config we have to get these traces:
[ejb_scope_and_rules.yml](https://github.com/inspectIT/inspectit-ocelot/files/4614656/ejb_scope_and_rules.txt)
And it returns (again thank to you) beautiful output stack with chain of execution.

As far, as I understand. 
I have to specify some actions to get arguments and return values. But I don't really know how to write that kind of thing. For now i reading secound time doc: https://inspectit.github.io/inspectit-ocelot/docs/instrumentation/rules#actions
If you can reply me if am I correct? Have I to find java way to get entry arguments and listen to return value? And how I suppose to add this into rules to call at right moment before/after method execute.

**Comment by GuazP** [comment]
I found of course these two parameters:
`_args` `_returnValue` but idk how to adapt this in general case.

**Comment by GuazP** [comment]
As far, as I try, my instrumentation looks that way:
inspectit:
  instrumentation:
    scopes:
      's_ejb_stateless_scope':
        type:
          annotations:
            - name: 'javax.ejb.Stateless'
              matcher-mode: EQUALS_FULLY
      's_ejb_stateful_scope':
        type:
          annotations:
            - name: "javax.ejb.Stateful"
              matcher-mode: EQUALS_FULLY
      's_ejb_singleton_scope':
        type:
          annotations:
            - name: "javax.ejb.Singleton"
              matcher-mode: EQUALS_FULLY
      's_ejb_messagedriven_scope':
        type:
          annotations:
            - name: "javax.ejb.MessageDriven"
              matcher-mode: EQUALS_FULLY
              
    rules:
      'r_ejb_rule':
        scopes:
          's_ejb_stateless_scope': true
          's_ejb_messagedriven_scope': true
          's_ejb_singleton_scope': true
          's_ejb_stateful_scope': true
        entry:
          'get_arguments':
            action: 'a_get_args'
        exit:
          'get_return':
            action: 'a_get_return'
        tracing:
          start-span: true
          
    actions:
      'a_get_args':
        input:
            _args: Object[]
        value: '_args'

      'a_get_return':
        input:
          _returnValue: Object
        value: '_returnValue'

**Comment by AlexanderWert** [comment]
Hi @GuazP,

I think it would be easier if we discuss this directly.
Can you please write us an e-mail to inspectit{at}novatec-gmbh.de, so we can setup a short zoom session?

**Comment by GuazP** [comment]
I can't contact you directly. Mailer Daemon block my email, whether I send it from my private or company email. Please send me other way to communicate: maciej.gravestone@wir.pl

**Comment by GuazP** [comment]
@AlexanderWert Still I can't reply, but i receive message from you.

Both are fine for me, I can match up.

Let's say 1:30 pm for example ?
