### ISSUE TITLE
configsrv ui / agent status / filter form should be able to use simple regex

### ISSUE THREAD

**Issue by mc-chaos** [inspectIT/inspectit-ocelot#745]
The search form at the agent-status tab should be able to use simple regex for filtering. Something like "applicationname*environment-name". If there is a agent list like this:
appA-testing-01
appB-testing-02
appA-qs-01
appB-qs-02

Then the filter for "app*-testing*" should show the first 2 lines and not the last 2 lines".

**Comment by mariusoe** [comment]
Implemented by #751
