### ISSUE TITLE
Allow users to specify whether agent mappings deliver files from the live or workspace branch

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#806]
Currently, agent mappings will only deliver files from the configuration server's "live" branch. This makes it difficult to test and develop new configurations because each change has to be approved before it is delivered to the agents. Furthermore, the continuous promotion of files will lead to a messy history of the underlying Git repository.

In order to solve this proble, the agent mappings should be extended so that it can be specified whether a mapping uses the live branch or the workspace branch for delivering configuration files. By default, an agent mapping should use the "live" branch for delivering configurations, in order to provide backward compatibility to the current functionality.

In this ticket, the configuration server should be extended to provide the previously described functionality.

**Comment by JonasKunz** [comment]
I think the default branch should be `workspace` for backwards compatibility, right?

**Comment by mariusoe** [comment]
Actually, it doesn't mather because as soon as you upgrade the config-server your the live branch is similar to the current working direcotry, thus, nothing will change.
As soon as a user starts modifying the configuration, the branches starts to differ. So, in this case you are right. The current behavior would be to use the worksapce branch as a default one.
