### ISSUE TITLE
InspectIT-Ocelot and Prometheus

### ISSUE THREAD

**Issue by n-feliciano** [inspectIT/inspectit-ocelot#931]
Hello,

I would like to ask for some help.

I am using Prometheus to monitor a Java application in 2 ways:
1-Through InspectIT-Ocelot agent, that has Prometheus bundled in and launches Prometheus at startup, and then sends the metrics to it.
2-Running Prometheus 2.21 separately from InspectIT-Ocelot, and then I don't think InspectIT-Ocelot sends the metrics to it.

When I use method 1, I can see the metrics on _http://localhost:port/metrics_, where I can see metrics like

`jvm_memory_committed{area="heap",host="DESKTOP-928RK73",host_address="192.168.222.1",id="PS Eden Space",service="InspectIT Agent",}
`

If I go to _http://localhost:port_ I get no user interface.
And then, when I try to pull the metrics from Grafana I get no data

When I use method 2, I can see the metrics on _http://localhost:9090/metrics_, where I can see go metrics like
```
go_info{version="go1.15.2"}
go_memstats_alloc_bytes
```
If I go to _http://localhost:9090_ I get the normal Prometheus user interface.
And then, I can pull the data from Grafana, but this are not the metrics I want.

Can anyone try to help me get the Prometheus bundled with InspectIT-Ocelot working with Grafana, or help me get an "outside Prometheus" working with my Java application with the InspectIT-Ocelot agent?

Thanks in advance,
Nuno

**Comment by mc-chaos** [comment]
Hi Nuno,

you know, that the inspect-IT JVM Agent only have a prometheus-Exporter? Like the Node-Exporter for server-metrics, but for the JVM-/Inspect-IT Metrics.
You always need a separate Prometheus instance  to scrape the metrics from the Exporter. Than you could connect your Grafana to the Prometheus. Means, you must have both (prometheus-exporter and prometheus).

Regards, Sascha

**Comment by n-feliciano** [comment]
Thank you very much, Sascha!
It is working now :)
