### ISSUE TITLE
Include boomerang-opentelemetry-plugin to distribution

### ISSUE THREAD

**Issue by mc-chaos** [inspectIT/inspectit-ocelot#935]
Include the boomerang-opentelemetry-plugin ( https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin ) to the distribution von inspect-IT EUM.

**Comment by mc-chaos** [comment]
Hi @mariusoe , is this not implemented?

Regards, Sascha

**Comment by mc-chaos** [comment]
@mariusoe : PING
I think, this is implemented. Right?
Regards, Sascha

**Comment by mariusoe** [comment]
Hi @mc-chaos 
sorry for the delay. I hadn't seen your comment.

You are right. This is already closed by #1224
