### ISSUE TITLE
Horizontal scaling and High Availability (HA) clustering for Ocelot Config Server

### ISSUE THREAD

**Issue by mnowrot** [inspectIT/inspectit-ocelot#945]
Is horizontal scaling and high availability clustering supported by Ocelot Config Server? If so, can I safely run multiple instances against a single working directory?

**Comment by mc-chaos** [comment]
Hi @mnowrot ,
we have a big inspect-IT environment in our company. So this was a point we have discussed. Our findings:
1. The agent do not need the configsrv to start, if the agent has before contact with the confisrv, there is a local copy for the agent-config. If there is no local copy, the agent is still there and is waiting for the configsrv, retrying to connect.
2. the config-file-directory (working directory) from the configsrv is a git-repo, so this way you could sync your different configsrv's. This task is not part of the inspect-IT solution, but could automated via scripts. This is the way we would solve this Task. We would solve with this way the "config drift" Problem for the stages. (every stage  in our infra has it on inspect-IT stack).
3. There is no technical need for HA of the configsrv. It is really stable and there are fallbacks (see 1.)
4. If you do HA, make a active/passive not active/active setup. It will help to get an overview (agent-status).
5. Do not share the working directory directly.

Regards

**Comment by mnowrot** [comment]
Thank you @mc-chaos - this replies my question fully.
