### ISSUE TITLE
Add a button to the Config UI that links to the documentation.

### ISSUE THREAD

**Issue by Patrick-Eichhorn** [inspectIT/inspectit-ocelot#975]
E.g. bottom left or top right of the Config UI

**Comment by JazzMina88** [comment]
![Screenshot 2022-06-29 at 14-07-37 inspectIT Ocelot Configuration Server Configuration](https://user-images.githubusercontent.com/95683924/176432553-c9f5ca53-baad-49ef-815d-4ca40460d8e5.png)
